environment:
  ## OpenFaaS Cloud: Communtiry Cluster ##
  gateway: "https://rlgerma92.io"
  origin: "https://rlgerma92.o6s.io"
  web_domain: "https://rlgerma92.o6s.io"
  external_domain: "https://rlgerma92.o6s.io"
  cookie_root_domain: ".o6s.io"
  external_redirect_domain: "https://rlgerma92.o6s.io/auth"
  websocket_server_url: "https://bootspace.herokuapp.com"
  ## Local environment ##
  # gateway: "http://gateway.openfaas:8080"
  # origin: "http://www.app.localhost:31112"
  # web_domain: "http://www.app.localhost:31112"
  # external_domain: "http://www.app.localhost:31112"
  # external_redirect_domain: "http://www.app.localhost:31112/function/auth"
  # cookie_root_domain: ".app.localhost"
  # websocket_server_url: "https://bootspace.herokuapp.com"
